Version: 2

#Models:
 # - name: dim_customers
 #   description: "Customer dimension."
  #  columns:
   #   - name: customer_id
    #    tests: [not_null, unique]
     # - name: customer_status
      #   - accepted_values:
        #      values: ["ACTIVE","INACTIVE"]


sources:
 - bfs_dw
   schema: 
   - bfs_silver
   tables:
     - table_name
     - table_name


   schema: 
   - bfs_gold
   tables:
     - table_name
     - table_name
